apiVersion: apps/v1
kind: Deployment
metadata:
  name: alfio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alfio
  template:
    metadata:
      labels:
        app: alfio
    spec:
      containers:
        - env:
            - name: POSTGRES_ENV_POSTGRES_DB
              value: alfio
            - name: POSTGRES_ENV_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cnpg-alfio-user
                  key: password
            - name: POSTGRES_ENV_POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cnpg-alfio-user
                  key: username
            - name: POSTGRES_PORT_5432_TCP_ADDR
              value: alfio-rw
            - name: POSTGRES_PORT_5432_TCP_PORT
              value: "5432"
            - name: SPRING_PROFILES_ACTIVE
              value: jdbc-session
            - name: JAVA_OPTS
              value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:+UseConcMarkSweepGC -Xmx256m -Xms256m"
          image: "alfio/alf.io:2.0-M4-2204-1"
          imagePullPolicy: IfNotPresent
          name: alfio
          ports:
            - name: web
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: web
          livenessProbe:
            httpGet:
              path: /healthz
              port: web
            initialDelaySeconds: 180
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              memory: 1Gi
