apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: alfio
  namespace: alfio
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: alfio
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
      type: Resource
