apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cnpg-alfio-user
  namespace: alfio
spec:
  encryptedData:
    password: AgBbXpJzteO0re+lbxO6lTxNcl0r4M3LHbnqhNTa9NPIUcc0+XTPutCMAtp2Ax/d6V6t6iDulhoFNpXyQ7uu0b0D5U1FzlkwlCWjRYKfznWc/RgmI5JiIc4fz+ChEktlju9pm9YfN8/SFbIPShs4kCLG7iqmuIw+50eoRcXC5Zi+TmwCtIIEdhNyIJIz35VMC4tI33OlhgQo8x435Y2g8/guakWx4DCUu1RHpuItlG1nVV6qLUn5ptbxqvjaPNLRZaxvwUd+HFmsXZ7Zdu72aNHkxGPFgZBbBYN7E29lqGi0wAVuta8Qw9simXOlZr7nh6CWQUFPXpiWl5eVuiVEzS+a1geX2IBgjwSTSn9rw/f+qFD3Ht2ZQmUn9+w/L8iE0lXy8NJKWcPFVMi1rbiVaauuN44eWhOgWMjHSGghr4mNI2kBpQNflKXda1NC2LxLI8eiMFiPYuaGTTdWQMhIBJcsAtOsV6eXk7dMcMopKBg8GcmW864eb5EqHzOwwWauz8You4YngGPJ0nL3uUbwVxL3QpCnsX9+hkv6CIFoeq23FQDmxStffFLpiX++mFo8HZxVHmjgtwWNm7qy5I/VFnI2Riq7GjuC06aFQH7s0JXKJ+hhIwhJ/RsJiEMiuZ6B0+RiF1yb2q2ZWxBNzGSfKqxmEVrdrAz38Q3FyzMWkcWu1LR+YjioM4Nbsyf18pC1+ZeemF/rk3hBeuBWYMwzJI8a3RwPzWQ0JCR/sROseXBjag==
    username: AgAZ3CMvsZdKiu9EeeSlHN2NocleSpu3rc3W6fKsEjxusUZXO6xRSLHxsuJ+S1xFXi79yu64nKK9U2seE9s+arFu7ZhD7ihZx8Mxc1DtR6rRw1SqvhadwFJfh5oqPXq79zOjvITh4DM+9eAP3vYb6VtUzLyLfzq4kN8Q/B/jLOlZcMlIsXLUW28MmhWFf2tZPrAXwrb/2yZ01mWS3Xtxm18HBleBQ55+qdaIXdjAkJPHJHiI1mWT0IBFIawuAzUyBvpD5KDqfo2Q/PthTV49Nyt1xoC6tdkZtRrJvcOYzqAh3g9OgSVf8z1FJOlb4jvLdS48OEdpycBxMVbXMGxNWRSKqW25EDcJnNGua3ClR7Ci2cb1LD3Wy8UUuA+sAxZ2yinleGsZHsuB+d7BbOvl/FjRDeIzwKjMz0bf2X73MX3vHNPlqCDEa/bRC27xEnDkl1uvHW16gZboBoxOlaQqpNTXkiFhLMK0cam9xwMoIUiAkl/3LyVNfgJZQ7JRJ62/UOzKx4mNkFjtFU+bID41c1ZUZgOn/n9KGQAVqqB5OX7WlsMVKUYVVaDt2bIOsI57MmI5/D8XQ7Olu2A7xezFOPUwHp0omQCTwkzs+wzIOyXkBCVz5pSztzaiqBCMBQfBpyiYBKA2VJHhzES2htqZ346fLzH41FF+xQZp0RfSZsuYLvHnXSjhCI0GeeYAGxK/uQe7+0s16A==
  template:
    metadata:
      creationTimestamp: null
      name: cnpg-alfio-user
      namespace: alfio

