apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  releaseName: weave-gitops
  chart:
    spec:
      chart: ./charts/gitops-server
      sourceRef:
        kind: GitRepository
        name: weave-gitops
        namespace: flux-system
  interval: 1m
  timeout: 5m
  values:
    rbac:
      impersonationResourceNames: ["gitops-reader", "admin"]
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
